name: Deploy RistoAI Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -e

            cd /home/ubuntu/risto-deploy/RistoAI

            echo "Updating source..."
            git fetch origin
            git reset --hard origin/main

            echo "Activating virtual environment..."
            source .venv/bin/activate

            echo "Installing Python packages..."
            pip install -r requirements.txt

            echo "Restarting API..."
            sudo systemctl restart risto-api.service

            echo "Checking service..."
            sudo systemctl status risto-api.service --no-pager

            echo "Deployment completed."
